// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_3aDlKeE8B6_6hqpcevpjMYwVmiCvPsY',
    appId: '1:637635627128:web:eb01a1fecddc9aea01058d',
    messagingSenderId: '637635627128',
    projectId: 'ecommerceapp-3e717',
    authDomain: 'ecommerceapp-3e717.firebaseapp.com',
    storageBucket: 'ecommerceapp-3e717.firebasestorage.app',
    measurementId: 'G-3XRHQNYGB2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrBeZdWyT8hk91gHKVxo0wGD6kD517tbI',
    appId: '1:637635627128:android:c705f2340cf45db801058d',
    messagingSenderId: '637635627128',
    projectId: 'ecommerceapp-3e717',
    storageBucket: 'ecommerceapp-3e717.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeOBOu-F3qhYZ_sB0RC4IF40cc0ot5KbY',
    appId: '1:637635627128:ios:a778534d13ec2fc001058d',
    messagingSenderId: '637635627128',
    projectId: 'ecommerceapp-3e717',
    storageBucket: 'ecommerceapp-3e717.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeOBOu-F3qhYZ_sB0RC4IF40cc0ot5KbY',
    appId: '1:637635627128:ios:a778534d13ec2fc001058d',
    messagingSenderId: '637635627128',
    projectId: 'ecommerceapp-3e717',
    storageBucket: 'ecommerceapp-3e717.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_3aDlKeE8B6_6hqpcevpjMYwVmiCvPsY',
    appId: '1:637635627128:web:06042170916154f901058d',
    messagingSenderId: '637635627128',
    projectId: 'ecommerceapp-3e717',
    authDomain: 'ecommerceapp-3e717.firebaseapp.com',
    storageBucket: 'ecommerceapp-3e717.firebasestorage.app',
    measurementId: 'G-E09P0Z2D07',
  );
}
